# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: pixi-build-api-version
  version: "2"

package:
  name: ${{ name }}
  version: ${{ version }}
  
source:
  url: https://github.com/prefix-dev/pixi-build-backends/archive/refs/tags/${{ name }}-v${{ version }}.tar.gz
  sha256: 679c7df3a012a99b46832e01e9beb5c7a19d52041c8a206b05fc476563078527

build:
  number: 0
  noarch: generic

about:
  homepage: https://github.com/prefix-dev/pixi-build-backends
  summary: The protocol version for pixi build backends.
  description: |
    This package is used to define the API version of the protocol used by pixi build backends.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  documentation: https://prefix-dev.github.io/pixi-build-backends
  repository: https://github.com/prefix-dev/pixi-build-backends

extra:
  recipe-maintainers:
    - baszalmstra
