# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: pixi-build-api-version
  version: "6"

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 0
  noarch: generic

tests:
  - package_contents:
      strict: true
      files: []

about:
  homepage: https://github.com/prefix-dev/pixi
  summary: The protocol version for pixi build backends.
  description: |
    This package is used to define the API version of the protocol used by pixi build backends.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  documentation: https://pixi.prefix.dev/latest/
  repository: https://github.com/prefix-dev/pixi

extra:
  recipe-maintainers:
    - baszalmstra
    - Hofer-Julian
